name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        dotnet-runtime: [win-x64, win-arm64, linux-x64, linux-arm64]
    runs-on: ubuntu-latest
    env:
      desktopBinariesName: Woohoo.Audio.Player-${{ github.event.release.tag_name }}-${{ matrix.dotnet-runtime }}
      consoleBinariesName: Woohoo.Audio.Player.Cli-${{ github.event.release.tag_name }}-${{ matrix.dotnet-runtime }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Desktop App - Build / Publish
      run: dotnet publish src/Woohoo.Audio.Player/Woohoo.Audio.Player.csproj -f net9.0 -r ${{ matrix.dotnet-runtime }} -c Release --self-contained -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=False

    - name: Console App - Build / Publish
      run: dotnet publish src/Woohoo.Audio.Player.Cli/Woohoo.Audio.Player.Cli.csproj -f net9.0 -r ${{ matrix.dotnet-runtime }} -c Release --self-contained -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=False

    - name: Desktop App - Zip binaries
      working-directory: ${{ github.workspace }}/bin/Release/Woohoo.Audio.Player/net9.0/${{ matrix.dotnet-runtime }}/publish
      run: zip -r ${{ github.workspace }}/bin/Release/Woohoo.Audio.Player/net9.0/${{ env.desktopBinariesName }}.zip *

    - name: Console App - Zip binaries
      working-directory: ${{ github.workspace }}/bin/Release/Woohoo.Audio.Player.Cli/net9.0/${{ matrix.dotnet-runtime }}/publish
      run: zip -r ${{ github.workspace }}/bin/Release/Woohoo.Audio.Player.Cli/net9.0/${{ env.consoleBinariesName }}.zip *

    - name: Desktop App - Upload binaries artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.dotnet-runtime }}
        path: bin/Release/Woohoo.Audio.Player/net9.0/${{ env.desktopBinariesName }}.zip

    - name: Console App - Upload binaries artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.dotnet-runtime }}
        path: bin/Release/Woohoo.Audio.Player.Cli/net9.0/${{ env.consoleBinariesName }}.zip

  release:
    name: Upload Release Assets
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download binaries artifacts for all runtimes
      uses: actions/download-artifact@v4
      with:
        path: release-artifacts
        merge-multiple: true

    - name: Display downloaded artifacts
      run: ls -R release-artifacts

    - name: Upload to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release-artifacts/*
